version: '3.8'

services:
  kube-tools:
    build:
      context: ..
      dockerfile: kubernetes/docker/Dockerfile
    environment:
      - KUBECONFIG=/kube/config
    volumes:
      - ../kubernetes:/manifests:ro
      - ${KUBECONFIG_PATH:-$HOME/.kube/config}:/kube/config:ro
