version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: round_robin_mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: round_robin_redis
    ports:
      - "6380:6379"

  backend-1:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - MODE=backend
      - BACKEND_PORT=5001
      - MONGO_URI=mongodb://mongo:27017/round_robin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  backend-2:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - MODE=backend
      - BACKEND_PORT=5001
      - MONGO_URI=mongodb://mongo:27017/round_robin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  backend-3:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - MODE=backend
      - BACKEND_PORT=5001
      - MONGO_URI=mongodb://mongo:27017/round_robin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  load-balancer:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - MODE=balancer
      - PORT=3000
      - BACKEND_TARGETS=http://backend-1:5001,http://backend-2:5001,http://backend-3:5001
      - REDIS_URL=redis://redis:6379
      - MONGO_URI=mongodb://mongo:27017/round_robin
    ports:
      - "3000:3000"
    depends_on:
      - backend-1
      - backend-2
      - backend-3

volumes:
  mongo-data:
